# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('icon.ico', '.')],
    hiddenimports=[
        'PySide6.QtCore', 'PySide6.QtWidgets', 'PySide6.QtGui',
        'watchdog', 'py7zr',
        'engine', 'ui', 'utils',
        'engine.config', 'engine.change_detector',
        'engine.backup_engine', 'engine.restore_engine',
        'engine.file_watcher', 'engine.backup_log',
        'engine.reconciliation',
        'ui.main_window', 'ui.tray_icon',
        'ui.restore_dialog', 'ui.orphan_dialog', 'ui.integrity_dialog',
        'utils.autostart',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='QiangBackup',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
